version: '3.9'

services:
  spark-master:
    build:
      context: ./Spark-master
    container_name: spark-master
    environment:
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_URL: spark://spark-master:7077
    ports:
      - "8080:8080"
      - "7077:7077"
      - "8888:8888"
  
  spark-worker:
    build:
      context: ./Spark-worker
    container_name: spark-worker
    environment:
      SPARK_MASTER: spark://spark-master:7077
      SPARK_WORKER_CORES: "2"
      SPARK_WORKER_MEMORY: "1G"
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
      - "7337:7337"